/**:
  ros__parameters:
    # 图像处理
    bin_low_threshold_: 150
    bin_high_threshold_: 255
    first_canny_low_threthold: 60
    first_canny_high_threthold: 100
    second_canny_low_threthold: 20
    second_canny_high_threthold: 100
    dilate_iterations: 3

    # 识别筛选
    min_area: 1000
    max_area: 10000
    offset_u: 0
    offset_v: 0
    max_contour_number: 5